name: DevSecOps CI/CD

on:
  push:
    branches: [ main ]

jobs:
  pipeline:
    runs-on: self-hosted

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: devsecops-app

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Generate Semantic Version
      id: version
      uses: paulhatch/semantic-version@v5.4.0
      with:
        tag_prefix: "v"
        format: "${major}.${minor}.${patch}"
        major_pattern: "BREAKING CHANGE"
        minor_pattern: "feat"

    - name: Print Version
      run: echo "VERSION=${{ steps.version.outputs.version }}"

    - name: Build Docker Image
      run: |
        VERSION=${{ steps.version.outputs.version }}
        OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')

        docker build --no-cache \
          -t ${REGISTRY}/${OWNER_LC}/${IMAGE_NAME}:$VERSION \
          -t ${REGISTRY}/${OWNER_LC}/${IMAGE_NAME}:latest \
          -f app/Dockerfile app/

    - name: Scan Image with Trivy
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: ghcr.io/minahilmehmood/devsecops-app:latest
        severity: CRITICAL,HIGH
        ignore-unfixed: true
        exit-code: "0"

    - name: Login to GHCR
      run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push Docker Images
      run: |
        VERSION=${{ steps.version.outputs.version }}
        OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')

        docker push ${REGISTRY}/${OWNER_LC}/${IMAGE_NAME}:$VERSION
        docker push ${REGISTRY}/${OWNER_LC}/${IMAGE_NAME}:latest

    - name: Create / Update GHCR Secret
      run: |
        kubectl delete secret ghcr-secret --ignore-not-found=true
        kubectl create secret docker-registry ghcr-secret \
          --docker-server=ghcr.io \
          --docker-username=${{ github.actor }} \
          --docker-password=${{ secrets.GHCR_PAT }} \
          --docker-email=dummy@example.com

    - name: Apply Kubernetes Manifests
      run: kubectl apply -f k8s/

    - name: Update Deployment Image
      run: |
        VERSION=${{ steps.version.outputs.version }}
        OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')

        kubectl set image deployment/devsecops-app \
          web=${REGISTRY}/${OWNER_LC}/${IMAGE_NAME}:$VERSION

    - name: Wait for Rollout
      run: kubectl rollout status deployment/devsecops-app
